version: '3.9'

services:
  trojan:
    image: trojangfw/trojan:latest
    ports:
      - "443:443"
    volumes:
      - ./trojan/config:/config
      - ./ssl:/ssl
      - ./trojan/wait_for_caddy.sh:/wait_for_caddy.sh
    working_dir: /config
    command: ["sh", "/wait_for_caddy.sh", "trojan", "config.json"]
    networks:
      - frontend
    depends_on:
      - caddy

  caddy:
    image: caddy/caddy:2.4.6-alpine
    ports:
      - "80:80"
    expose:
      - 4433
    environment:
      - DOMAIN_HOSTNAME=${DOMAIN_NAME}
      - PASSWD_BCRYPTED=${PASSWD_BCRYPTED}
      - USERNAME=${USERNAME}
    networks:
      - frontend
    volumes:
      - ./caddy/config:/var/www/${DOMAIN_NAME:-localhost}/config:ro
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
      - caddy_data:/data       # named volume
      - caddy_config:/config   # named volume

networks:
  frontend:

volumes:
  caddy_data:
  caddy_config: