version: '3.9'
services:
  clash-profiles:
    expose:
      - "80"
    restart: unless-stopped
    build: ./$CONSOLIDATION_REPOSITORY_NAME/
    environment:
      NODE_ENV: production
      EXPIRE: ${CONSOLIDATION_CUTOFF_TIMESTAMP}
    networks:
      - traefik
    volumes:
      - ./external-rulesets:/app/external-rulesets
      - ${CONSOLIDATION_PROFILES_OUTPUT:-./profiles}:/app/output
      - ${CONSOLIDATION_PROFILES_SRC:-./profiles.js}:/app/profiles.js
      - ${CONSOLIDATION_INJECTIONS_SRC:-./injections.yml}:/app/injections.yml
      - ${CONSOLIDATION_WRANGLER_CONFIG:-./wrangler.toml}:/app/wrangler.toml
    labels:
      traefik.http.routers.clash-profiles.rule: ${CONSOLIDATION_ROUTER_RULE_HOSTS} && PathPrefix(`/.profiles`)
      traefik.http.routers.clash-profiles.entryPoints: "websecure"
      traefik.http.routers.clash-profiles.tls: true
      traefik.http.routers.clash-profiles.tls.certresolver: cfresolver
      traefik.http.routers.clash-profiles.service: clash-profiles 
      traefik.http.routers.clash-profiles.middlewares: clash-profiles-access-auth  
      traefik.http.middlewares.clash-profiles-access-auth.basicauth.usersfile: /credentials/clash-profiles-access
    logging:
      options:
        max-size: "30m"
        max-file: "3"
networks:
  traefik:
    external: true