version: '3.9'

services:
  trojan:
    image: trojangfw/trojan:latest
    ports:
      - "443:443"
    volumes:
      - ./trojan/config:/config
      - ./ssl:/ssl
      - ./trojan/wait-for-certificates.sh:/wait-for-certificates.sh
    working_dir: /config
    environment:
      DOMAIN_NAME: $DOMAIN_NAME
    command: ["sh", "/wait-for-certificates.sh", "trojan", "config.json"]
    networks:
      - frontend
    depends_on:
      - caddy
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  caddy:
    image: caddy/caddy:2.4.0-alpine
    ports:
      - "80:80"
    expose:
      - 8080
    environment:
      - DOMAIN_HOSTNAME=${DOMAIN_NAME}
      - PASSWD_BCRYPTED=${PASSWD_BCRYPTED}
      - USERNAME=${USERNAME}
      - EXPIRE=${EXPIRE}
      - DOH_PATH=${DOH_PATH}
      - FILENAME=${FILENAME}
    networks:
      - frontend
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./caddy/config:/var/www/${DOMAIN_NAME:-localhost}/.config:ro
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
      - caddy_data:/data       # named volume
      - caddy_config:/config   # named volume
    restart: unless-stopped
  doh:
    image: satishweb/doh-server:alpine
    expose:
      - 8053
    environment:
      UPSTREAM_DNS_SERVER: "udp:8.8.8.8:53"
      DOH_HTTP_PREFIX: "${DOH_PATH}"
      DOH_SERVER_LISTEN: ":8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "false"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:

volumes:
  caddy_data:
  caddy_config: